"""Rendered fetching -- runs the page's JavaScript and measures where its text landed.

This module exists for two reasons, and the second is the important one:

1. Client-rendered pages have no content in their static HTML.
2. **Reading order needs geometry.** Source order is not visual order (MEMORY.md D10), and
   the only way to know where text actually sits is to lay the page out and measure it.

Binding measurements back to parsed elements
--------------------------------------------
Rects are collected in the browser but consumed by lxml, so the two need a shared key.
Recomputing an XPath in JavaScript to match lxml's `getpath()` output is fragile -- the
formats differ over when an index is emitted, and a mismatch fails silently by yielding no
geometry at all.

Instead the browser stamps every element with a `data-wg-id` attribute *before* serialising
the DOM. The attribute survives into the HTML we parse, so each element can be found again
and keyed by whatever path lxml itself produces. The key is generated by the same library
that consumes it, which removes the mismatch entirely.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Final, Literal
from urllib.parse import urlsplit

from webgraph.fetch import browser as browser_module
from webgraph.fetch import guard
from webgraph.fetch.browser import shared_browser
from webgraph.types import Rect

__all__ = [
    "PLAYWRIGHT_AVAILABLE",
    "RenderConfig",
    "RenderResult",
    "geometry_by_xpath",
    "render_page",
]

try:  # pragma: no cover - import guard depends on optional extra
    from playwright.sync_api import sync_playwright

    PLAYWRIGHT_AVAILABLE = True
except ImportError:  # pragma: no cover
    PLAYWRIGHT_AVAILABLE = False

MARKER_ATTRIBUTE: Final[str] = "data-wg-id"
GATE_ATTRIBUTE: Final[str] = "data-wg-gate"
BREAK_ATTRIBUTE: Final[str] = "data-wg-brk"
"""Stamped on elements the browser lays out as their own box, so the parser can tell a line
boundary from inline flow. See `_COLLECT_SCRIPT`."""

_REVEAL_SCRIPT: Final[str] = """
() => {
  // Open content the page collapsed, without clicking anything.
  //
  // Accordions, FAQ sections and `<details>` blocks hold real content that no fetch and no
  // renderer sees, because it is `display:none` until someone interacts. Clicking is the
  // obvious way to reach it and the wrong one: a click can navigate, submit a form, open a
  // dialog that blocks the driver, or fire an analytics event on someone else's site.
  //
  // Everything here is a property or attribute change on the page's own DOM. Nothing is
  // clicked, no handler is invoked, and the page cannot navigate as a result.
  let opened = 0;

  for (const details of document.querySelectorAll('details:not([open])')) {
    details.open = true;
    opened++;
  }

  // ARIA disclosure pattern: a control says what it controls, and the panel says it is
  // hidden. Both halves are declared by the page, so honouring them is reading the page's
  // own description of itself rather than guessing at class names.
  for (const control of document.querySelectorAll('[aria-expanded="false"][aria-controls]')) {
    const ids = (control.getAttribute('aria-controls') || '').split(/\\s+/);
    let revealed = false;
    for (const id of ids) {
      const panel = document.getElementById(id);
      if (!panel) continue;
      panel.removeAttribute('hidden');
      if (panel.getAttribute('aria-hidden') === 'true') panel.setAttribute('aria-hidden', 'false');
      const style = window.getComputedStyle(panel);
      if (style.display === 'none') panel.style.setProperty('display', 'block', 'important');
      if (style.visibility === 'hidden') panel.style.setProperty('visibility', 'visible', 'important');
      if (parseFloat(style.height) === 0 && panel.scrollHeight > 0) {
        panel.style.setProperty('height', 'auto', 'important');
        panel.style.setProperty('overflow', 'visible', 'important');
      }
      revealed = true;
    }
    if (revealed) { control.setAttribute('aria-expanded', 'true'); opened++; }
  }

  return opened;
}
"""

_GATE_PROBE: Final[str] = r"""
() => {
  // Assess whether the mounted page is a gate rather than the site, and mark the controls
  // that would open it.
  //
  // The case this exists for: a client-rendered app whose entire mounted DOM is a first-run
  // interstitial -- a persona or role picker, a region or currency selector, an age gate, an
  // onboarding wizard. The real content is *unmounted*, not hidden, so `_REVEAL_SCRIPT`
  // cannot reach it: there is no collapsed panel to open, and nothing in the DOM to reveal.
  // Measured on zerotoonepmtoolkit.app, whose 21 routes all render the same persona modal:
  // 1,137 characters of text and ZERO internal links, against ~32,900 characters behind it.
  //
  // Two signals, both structural rather than textual, so this does not depend on guessing at
  // wording in any particular language:
  //
  //   1. Almost no internal links. A real page of a real site carries navigation. A gate
  //      screen carries none, because the nav lives in the subtree that has not mounted.
  //   2. Little text.
  //
  // Requiring both matters. A long article legitimately has few outbound links, and a link
  // hub legitimately has little prose; only the conjunction says "nothing has mounted yet".
  const MARK = 'data-wg-gate';
  for (const el of document.querySelectorAll('[' + MARK + ']')) el.removeAttribute(MARK);

  const text = ((document.body && document.body.innerText) || '').trim();
  const origin = location.origin;
  const internal = new Set();
  for (const a of document.querySelectorAll('a[href]')) {
    const raw = a.getAttribute('href') || '';
    if (!raw || raw.startsWith('#') || raw.startsWith('javascript:')) continue;
    let resolved;
    try { resolved = new URL(raw, location.href); } catch (e) { continue; }
    if (resolved.origin !== origin) continue;
    const path = resolved.pathname.replace(/\/$/, '');
    if (path && path !== location.pathname.replace(/\/$/, '')) internal.add(path);
  }

  // Candidate controls, ordered by how likely they are to be the thing that opens the gate.
  //
  // Deliberately excluded, because clicking them does something to somebody's site rather
  // than to the page:
  //   - anything inside a <form>, which may submit;
  //   - anchors carrying a real href, which navigate -- an ordinary link is not a gate;
  //   - controls whose accessible name reads as a transaction, a refusal or a sign-out.
  // The exclusions are on what the element *is*, not on what it says, except for the last,
  // which is a narrow deny-list rather than an attempt to understand the label.
  const DENY = /(buy|purchase|checkout|subscribe|pay|donate|delete|remove|sign\s*out|log\s*out|unsubscribe|reject|decline|deny|refuse|exit|cancel)/i;

  const viewport = window.innerWidth * window.innerHeight;
  const scored = [];
  const controls = document.querySelectorAll(
    'button, [role="button"], [role="radio"], [role="option"], [tabindex]:not([tabindex="-1"]), a:not([href])'
  );

  for (const el of controls) {
    if (el.closest('form')) continue;
    if (el.tagName === 'A' && el.getAttribute('href')) continue;
    if (el.disabled) continue;

    const style = window.getComputedStyle(el);
    if (style.display === 'none' || style.visibility === 'hidden' || style.opacity === '0') continue;
    const box = el.getBoundingClientRect();
    if (box.width < 24 || box.height < 16) continue;

    const label = (el.innerText || el.getAttribute('aria-label') || '').trim();
    if (DENY.test(label)) continue;

    // A control sitting inside a fixed or absolutely-positioned layer that covers much of
    // the viewport is the classic modal shape, and is tried first.
    let overlay = 0;
    for (let node = el; node && node !== document.body; node = node.parentElement) {
      const s = window.getComputedStyle(node);
      if (s.position === 'fixed' || s.position === 'absolute') {
        const b = node.getBoundingClientRect();
        if (b.width * b.height > viewport * 0.5) { overlay = 1; break; }
      }
    }
    scored.push({ el: el, overlay: overlay, area: box.width * box.height });
  }

  scored.sort((a, b) => (b.overlay - a.overlay) || (b.area - a.area));

  const marks = [];
  for (let i = 0; i < scored.length && marks.length < 8; i++) {
    scored[i].el.setAttribute(MARK, String(marks.length));
    marks.push(String(marks.length));
  }

  return { textLength: text.length, internalLinks: internal.size, candidates: marks };
}
"""

GATE_MAX_TEXT: Final[int] = 4000
"""Below this much text, together with almost no internal links, a page may be a gate.

Generous on purpose. The check is a *trigger for looking*, not a verdict: nothing is kept
unless a click measurably improves the page, so a false trigger costs one guarded click and
changes no output."""

GATE_MAX_LINKS: Final[int] = 1
"""Internal links above which the page is treated as real navigation, not a gate.

One, not two, and the difference is not cosmetic. At two, a small site's ordinary page --
2,161 characters and two nav links, in `test_gates.py`'s ungated fixture -- was reported as
looking gated. Nothing was clicked, because the accept test still refused it, but the engine
was describing a perfectly normal page as suspicious.

The measured gate has **zero** internal links, because its navigation lives in the subtree
that never mounted. Allowing one covers a gate that still renders a logo linking home."""

GATE_MIN_GAIN: Final[float] = 1.5
"""How much better the page must get before a click is kept.

A gate that opens reveals the whole site, so the real signal is large -- 1,137 characters to
2,344 with 0 links becoming 21 on the measured case. Requiring a decisive improvement keeps
this from accepting a click that merely opened a tooltip."""


MAX_RECORDED_REQUESTS: Final[int] = 400
"""Requests kept for fingerprinting. Only distinct hosts and paths carry information, and
an asset-heavy page can issue thousands."""

_COLLECT_SCRIPT: Final[str] = """
() => {
  const MARKER = 'data-wg-id';
  const BREAK = 'data-wg-brk';
  const rects = {};
  let counter = 0;

  // Walk into open shadow roots as well as the light DOM.
  //
  // A TreeWalker stops at a shadow boundary and `outerHTML` does not serialise across one,
  // so a component that renders its content inside a shadow root was previously invisible
  // *twice over*: absent from the HTML lxml parses, and absent from the geometry map. The
  // loss is total rather than partial, and nothing reported it. Web Almanac 2024 puts shadow
  // DOM on 2.51% of mobile pages, up 6x in two years, and custom elements on 7.9%.
  //
  // getBoundingClientRect() inside a shadow root already returns page coordinates, so the
  // rectangles need no transform.
  const shadowRoots = [];
  const nodes = [document.documentElement];
  const descend = (root) => {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT);
    while (walker.nextNode()) {
      const el = walker.currentNode;
      nodes.push(el);
      if (el.shadowRoot) { shadowRoots.push(el.shadowRoot); descend(el.shadowRoot); }
    }
  };
  descend(document.documentElement);

  for (const el of nodes) {
    const id = String(counter++);
    el.setAttribute(MARKER, id);

    const style = window.getComputedStyle(el);

    // Mark elements the browser lays out as their own box.
    //
    // lxml's `text_content()` concatenates descendants with nothing between them, so a
    // navigation of `<a>Mac</a><a>iPad</a><a>iPhone</a>` arrives as `MaciPadiPhone` -- the
    // words destroyed, not merely unwanted. Measured on apple.com/airpods-pro, whose whole
    // nav came out as `AppleStoreShopShop the LatestMaciPadiPhoneApple Watch...`.
    //
    // A separator cannot be inserted between every pair of elements, because inline siblings
    // genuinely do run together: `<b>bold</b><i>italic</i>` renders as `bolditalic` and
    // splitting it would be the same corruption in the other direction. What decides is the
    // computed `display`: a block-level box starts a new line, an inline one does not. That
    // is the rule `innerText` itself follows, and it is a measurement of this page rather
    // than an assumption about markup.
    const display = style.display;
    if (display && display !== 'inline' && display !== 'inline-block' &&
        display !== 'contents' && display !== 'none') {
      el.setAttribute(BREAK, '1');
    }

    if (style.display === 'none' || style.visibility === 'hidden' || style.opacity === '0') {
      continue;
    }
    const box = el.getBoundingClientRect();
    if (box.width <= 0 || box.height <= 0) continue;

    rects[id] = {
      // Page-relative, not viewport-relative: a scrolled viewport would otherwise
      // report negative coordinates for content above the fold.
      x: box.left + window.scrollX,
      y: box.top + window.scrollY,
      width: box.width,
      height: box.height,
    };
  }
  // Library versions are frequently only available at runtime. `jquery.min.js` carries no
  // version in its filename, but `jQuery.fn.jquery` reports it exactly. Reading these while
  // the page is live is the only reliable way to get them.
  const globals = {};
  // Sentinel for "this is loaded but exposes no version". The Python side treats any value
  // that does not begin with a digit as presence without a version.
  const PRESENT = 'present';
  const probe = (name, fn) => { try { const v = fn(); if (v) globals[name] = String(v); } catch (e) {} };

  // Every global the page added, found by diffing against a pristine window.
  //
  // This is the signal that closes most of the gap with a browser extension. Hand-written
  // probes only find what someone thought to ask for; the diff finds `window.Tinybird`,
  // `window.__reactRouterVersion` and `window.lenisVersion` without anyone naming them
  // first, and the rules then map names to technologies.
  //
  // The baseline comes from a blank same-origin iframe rather than a hard-coded list,
  // because the set of standard globals differs by browser and by version.
  let customGlobals = [];
  try {
    const frame = document.createElement('iframe');
    frame.setAttribute('aria-hidden', 'true');
    frame.style.cssText = 'display:none;width:0;height:0';
    document.body.appendChild(frame);
    const baseline = new Set(Object.keys(frame.contentWindow));
    frame.remove();
    // Cap the list: a page that assigns hundreds of globals is doing something unusual, and
    // the interesting names are always near the front of the enumeration order anyway.
    customGlobals = Object.keys(window).filter((k) => !baseline.has(k)).slice(0, 400);
  } catch (e) { /* CSP can forbid the iframe; the explicit probes still apply. */ }

  probe('jQuery', () => window.jQuery && window.jQuery.fn && window.jQuery.fn.jquery);
  probe('React', () => window.React && window.React.version);
  probe('Vue.js', () => window.Vue && window.Vue.version);
  probe('Angular', () => window.ng && window.ng.version && window.ng.version.full);
  probe('Bootstrap', () => window.bootstrap && window.bootstrap.Tooltip && window.bootstrap.Tooltip.VERSION);
  probe('Modernizr', () => window.Modernizr && window.Modernizr._version);
  probe('Lodash', () => window._ && window._.VERSION);
  probe('Moment.js', () => window.moment && window.moment.version);
  probe('D3', () => window.d3 && window.d3.version);
  probe('GSAP', () => window.gsap && window.gsap.version);
  probe('Next.js', () => window.next && window.next.version);
  probe('Swiper', () => window.Swiper && window.Swiper.version);
  probe('PostHog', () => window.posthog && (window.posthog.version || window.posthog.config ? (window.posthog.version || PRESENT) : null));
  probe('Lenis', () => window.Lenis && (window.Lenis.version || PRESENT));
  probe('core-js', () => window['__core-js_shared__'] && PRESENT);
  probe('Alpine.js', () => window.Alpine && (window.Alpine.version || PRESENT));
  probe('Three.js', () => window.THREE && (window.THREE.REVISION || PRESENT));
  probe('Framer Motion', () => window.__FRAMER_MOTION__ && PRESENT);

  // Bundled frameworks expose no global at all -- a Vite build of React has no
  // `window.React`. They do leave private properties on the DOM nodes they own, which is
  // the only honest evidence that the framework is *running* rather than merely mentioned.
  const domKeyed = (prefixes) => {
    const roots = [document.body, document.getElementById('root'), document.getElementById('app')];
    const seen = [];
    for (const root of roots) {
      if (!root) continue;
      seen.push(root);
      for (let i = 0; i < root.children.length && seen.length < 40; i++) seen.push(root.children[i]);
    }
    for (const el of seen) {
      for (const key of Object.keys(el)) {
        for (const prefix of prefixes) {
          if (key.startsWith(prefix)) return true;
        }
      }
    }
    return false;
  };

  probe('React', () => {
    if (window.React && window.React.version) return window.React.version;
    return domKeyed(['__reactContainer$', '__reactFiber$', '__reactProps$', '__reactInternalInstance$'])
      ? PRESENT : null;
  });
  probe('Preact', () => domKeyed(['__preactattr_', '_prevVNode', '__k']) && !window.React ? PRESENT : null);
  probe('Vue.js', () => {
    if (window.Vue && window.Vue.version) return window.Vue.version;
    const el = document.querySelector('#app, [data-v-app]');
    return el && el.__vue_app__ ? (el.__vue_app__.version || PRESENT) : null;
  });
  probe('Svelte', () => document.querySelector('[class*=svelte-]') || domKeyed(['__svelte_meta']) ? PRESENT : null);
  probe('React Router', () => {
    if (window.__reactRouterVersion) return String(window.__reactRouterVersion);
    if (window.__reactRouterContext || window.__staticRouterHydrationData) return PRESENT;
    return document.querySelector('[data-discover="true"]') ? PRESENT : null;
  });

  // Versions, where the library exposes one somewhere other than a bare `.version`.
  probe('Facebook Pixel', () => window.fbq && window.fbq.version);
  probe('core-js', () => {
    const shared = window['__core-js_shared__'];
    if (!shared) return null;
    const versions = shared.versions;
    if (Array.isArray(versions) && versions.length && versions[0].version) return versions[0].version;
    return PRESENT;
  });
  probe('Lenis', () => window.lenisVersion || (window.lenis || document.documentElement.classList.contains('lenis') ? PRESENT : null));
  probe('PostHog', () => {
    const ph = window.posthog;
    if (ph) return ph.version || (ph.LIB_VERSION) || PRESENT;
    return window.__PosthogExtensions__ || window._POSTHOG_REMOTE_CONFIG ? PRESENT : null;
  });
  probe('Tinybird', () => window.Tinybird && PRESENT);

  const scripts = Array.from(document.scripts).map((s) => s.src).filter(Boolean).slice(0, 60);
  const links = Array.from(document.querySelectorAll('link[rel][href]'))
    .map((l) => l.rel + ' ' + l.href).slice(0, 60);

  // Serialise shadow roots as `<template shadowrootmode>`, which the Python side unwraps.
  // `getHTML` is Chromium 125+; without it we fall back to the light DOM only rather than
  // failing, and the shadow content is lost as it always was.
  let serialized;
  try {
    serialized = (shadowRoots.length && typeof document.documentElement.getHTML === 'function')
      ? document.documentElement.getHTML({ serializableShadowRoots: true, shadowRoots })
      : document.documentElement.outerHTML;
  } catch (e) {
    serialized = document.documentElement.outerHTML;
  }

  return {
    rects,
    shadowRoots: shadowRoots.length,
    html: serialized,
    globals,
    customGlobals,
    scripts,
    links,
  };
}
"""


@dataclass(frozen=True, slots=True)
class RenderConfig:
    timeout_ms: int = 30_000
    wait_until: Literal["commit", "domcontentloaded", "load", "networkidle"] = "load"
    """`load`, not `networkidle`.

    `networkidle` waits for 500ms of no network activity, which **never happens** on sites
    with analytics beacons, polling, websockets or video preloading. Measured against 24 real
    sites it timed out on 5 of them (21%) -- Shopify, Squarespace, Stripe, python.org and
    Figma -- losing those pages entirely. `load` plus an explicit settle is slightly earlier
    but actually fires."""

    viewport_width: int = 1440
    viewport_height: int = 900
    """Width matters for reading order -- a narrow viewport collapses a multi-column layout
    into one column, which changes the correct answer."""

    settle_ms: int = 900
    """Pause after load to let hydration and layout settle before measuring.

    Carries the weight that `networkidle` used to: most client-side frameworks finish
    hydrating within a few hundred milliseconds of `load`, and measuring before that captures
    the pre-hydration layout."""

    dismiss_gates: bool = True
    """Open a first-run interstitial that is blocking the page from mounting.

    On by default, on the same asymmetric-cost reasoning that biases `_needs_render` toward
    rendering: a gate left closed loses essentially the whole site -- 97% of the text and
    *every* internal link on the measured case -- while a wrongly-suspected gate costs one
    guarded click and is discarded unless it measurably improves the page.

    This is the one place the engine clicks anything, and `_REVEAL_SCRIPT`'s reasons for
    refusing to click still stand, so the click is fenced in four ways: it only happens on a
    page that has almost no text *and* almost no internal links; candidates inside a `<form>`
    or carrying a real `href` are never chosen; labels reading as a transaction, refusal or
    sign-out are excluded; and the result is thrown away unless the page gets decisively
    better. A click that navigates off-origin is reverted.
    """

    reveal_collapsed: bool = False
    """Open `<details>` and ARIA disclosure panels before measuring.

    Reaches content the page hides until someone interacts, without clicking anything -- see
    `_REVEAL_SCRIPT` for why clicking is the wrong tool. Off until measured; see MEMORY.md.
    """

    user_agent: str | None = None
    headless: bool = True
    reuse_browser: bool = True
    """Reuse the calling thread's browser rather than launching one per page.

    Launch is a fixed cost per page -- see `fetch/browser.py` for why the reuse is
    thread-local. Disable it to isolate a page that crashes the browser."""

    block_resources: tuple[str, ...] = ("image", "media", "font")
    """Skipped to cut bandwidth and time. Fonts are blocked deliberately: metrics shift
    slightly without them, but not enough to change column structure."""


@dataclass(frozen=True, slots=True)
class RenderResult:
    url: str
    html: str
    """Serialised *after* marker attributes were stamped, so the markers are present."""

    rects: dict[str, Rect]
    """Keyed by marker id, not XPath. Use `geometry_by_xpath` to rekey for the pipeline."""

    ok: bool
    error: str | None = None
    globals: dict[str, str] = field(default_factory=dict)
    """Library versions read from live JavaScript globals -- the only place most of them
    appear. `jquery.min.js` has no version in its filename; `jQuery.fn.jquery` has it exactly."""

    custom_globals: tuple[str, ...] = ()
    """Every global the page added, diffed against a pristine window.

    Hand-written probes only find what someone thought to name. This finds the rest --
    `Tinybird`, `__reactRouterVersion`, `lenisVersion` -- and is what closes most of the gap
    with a browser extension that can read the live heap."""

    requests: tuple[str, ...] = ()
    """Every URL the page requested while loading.

    A third-party service is frequently invisible in the markup and unmistakable in the
    network log: PostHog arrives as `us-assets.i.posthog.com/array/.../config.js`, and
    Cloudflare's bot management as a `/cdn-cgi/challenge-platform/` script."""

    cookies: dict[str, str] = field(default_factory=dict)
    """Cookies present after load, from the browser jar rather than the document's own
    `Set-Cookie`. Cookies set by a third-party script never appear in the main response."""

    scripts: tuple[str, ...] = ()
    """`src` of every script element after hydration, including ones injected at runtime."""

    links: tuple[str, ...] = ()
    """`rel href` of every link element, for manifest, preconnect and stylesheet signals."""

    shadow_roots: int = 0
    """Open shadow roots pierced while measuring. Recorded because their content is invisible
    to every DOM-based extractor that does not go looking for it, so a caller comparing
    against another tool should know when this page had any."""

    gate_dismissed: bool = False
    """True when an interstitial was opened to reach the page. Recorded rather than silent:
    the caller is entitled to know the measured page required a click to exist."""

    gate_note: str | None = None
    """What was observed, when a gate was suspected -- whether or not it opened."""


def _open_gate(page: Any) -> tuple[bool, str | None]:
    """Try to open a first-run interstitial that is stopping the page from mounting.

    Returns (whether the page was opened, what was observed). Never raises: a page that
    cannot be probed is simply not a page with a gate we can open, and a failed click must
    not cost the caller the render it already has.

    The accept test is the whole safety argument. A click is kept only when the page gets
    decisively better on *both* axes the probe measures -- text and internal links -- so a
    click that opened a tooltip, dismissed a cookie bar or did nothing at all leaves the
    result unchanged rather than being reported as a success.
    """
    try:
        before = page.evaluate(_GATE_PROBE)
    except Exception:
        return False, None

    text_before = int(before.get("textLength") or 0)
    links_before = int(before.get("internalLinks") or 0)
    candidates = list(before.get("candidates") or ())

    if text_before > GATE_MAX_TEXT or links_before > GATE_MAX_LINKS:
        return False, None
    if not candidates:
        return False, (
            f"page looks gated ({text_before} chars, {links_before} internal links) "
            "but no control was found to open it"
        )

    origin_before = urlsplit(page.url)

    for marker in candidates:
        try:
            page.click(f"[{GATE_ATTRIBUTE}='{marker}']", timeout=2_000, no_wait_after=True)
        except Exception:
            continue

        try:
            page.wait_for_timeout(600)
            after = page.evaluate(_GATE_PROBE)
        except Exception:
            continue

        # A click that left the origin followed a link rather than opening a gate. Go back
        # and treat it as a failed candidate; the guard would refuse the new address anyway.
        landed = urlsplit(page.url)
        if landed.netloc != origin_before.netloc:
            try:
                page.go_back(timeout=5_000)
                page.wait_for_timeout(400)
            except Exception:
                pass
            continue

        text_after = int(after.get("textLength") or 0)
        links_after = int(after.get("internalLinks") or 0)

        opened = (
            text_after >= max(text_before * GATE_MIN_GAIN, text_before + 200)
            and links_after > links_before
        )
        if opened:
            return True, (
                f"opened an interstitial: {text_before} -> {text_after} chars, "
                f"{links_before} -> {links_after} internal links"
            )

    return False, (
        f"page looks gated ({text_before} chars, {links_before} internal links); "
        f"{len(candidates)} control(s) tried, none opened it"
    )


def render_page(url: str, *, config: RenderConfig | None = None) -> RenderResult:
    """Load `url` in a headless browser and measure every visible element."""
    if not PLAYWRIGHT_AVAILABLE:
        return RenderResult(
            url=url,
            html="",
            rects={},
            ok=False,
            error="playwright is not installed; install the 'render' extra",
        )

    try:
        guard.check_url(url)
    except guard.BlockedHostError as exc:
        return RenderResult(url=url, html="", rects={}, ok=False, error=str(exc))

    config = config or RenderConfig()

    def _measure(browser: Any) -> dict[str, Any]:
        """One page, in its own context so nothing leaks between pages of a crawl."""
        context = browser.new_context(
            viewport={"width": config.viewport_width, "height": config.viewport_height},
            user_agent=config.user_agent,
        )
        try:
            page = context.new_page()

            # The network log is a first-class fingerprinting signal, not diagnostics: a
            # third-party service is often invisible in the markup and unmistakable here.
            # Capped, because an image-heavy page can issue hundreds of requests and only
            # the distinct hosts and paths carry information.
            requests: list[str] = []

            def _record(request: Any) -> None:
                if len(requests) < MAX_RECORDED_REQUESTS:
                    requests.append(str(request.url))

            page.on("request", _record)

            if config.block_resources:
                blocked = set(config.block_resources)
                page.route(
                    "**/*",
                    lambda route: (
                        route.abort()
                        if route.request.resource_type in blocked
                        else route.continue_()
                    ),
                )

            response = page.goto(url, timeout=config.timeout_ms, wait_until=config.wait_until)
            # The browser follows redirects itself, so the address that was checked above
            # is not necessarily the one that answered. Raising here is caught by the
            # handler at the bottom and reported as a failed render.
            if response is not None:
                guard.check_url(str(response.url))
            if config.settle_ms:
                page.wait_for_timeout(config.settle_ms)

            if config.reveal_collapsed:
                try:
                    revealed = int(page.evaluate(_REVEAL_SCRIPT) or 0)
                except Exception:
                    revealed = 0
                if revealed:
                    # Let layout settle: opening a panel reflows everything below it, and
                    # reading order is measured from geometry.
                    page.wait_for_timeout(250)

            gate_dismissed = False
            gate_note: str | None = None
            if config.dismiss_gates:
                gate_dismissed, gate_note = _open_gate(page)
                if gate_dismissed:
                    # Mounting the real page reflows everything, and reading order is
                    # measured from geometry.
                    page.wait_for_timeout(config.settle_ms or 500)

            payload = dict(page.evaluate(_COLLECT_SCRIPT))
            payload["gate_dismissed"] = gate_dismissed
            payload["gate_note"] = gate_note
            payload["requests"] = requests
            # From the jar, not from the document's own `Set-Cookie`: a cookie written by a
            # third-party script never appears in the main response headers.
            payload["cookies"] = {
                str(cookie.get("name", "")): str(cookie.get("value", ""))
                for cookie in context.cookies()
            }
            return payload
        finally:
            context.close()

    try:
        shared = shared_browser(headless=config.headless) if config.reuse_browser else None
        if shared is not None:
            payload: dict[str, Any] = _measure(shared)
        else:
            # No slot free, reuse disabled, or the shared launch failed: fall back to a
            # private browser so a render never depends on the pool being available.
            with sync_playwright() as driver:
                browser = driver.chromium.launch(
                    headless=config.headless, args=list(browser_module.LAUNCH_ARGS)
                )
                try:
                    payload = _measure(browser)
                finally:
                    browser.close()

        rects = {
            key: Rect(
                x=float(value["x"]),
                y=float(value["y"]),
                width=float(value["width"]),
                height=float(value["height"]),
            )
            for key, value in payload["rects"].items()
        }
        raw_globals = payload.get("globals") or {}
        return RenderResult(
            url=url,
            html=str(payload["html"]),
            rects=rects,
            ok=True,
            globals={str(k): str(v) for k, v in raw_globals.items()},
            custom_globals=tuple(str(name) for name in payload.get("customGlobals") or ()),
            requests=tuple(str(item) for item in payload.get("requests") or ()),
            cookies={str(k): str(v) for k, v in (payload.get("cookies") or {}).items()},
            scripts=tuple(str(item) for item in payload.get("scripts") or ()),
            links=tuple(str(item) for item in payload.get("links") or ()),
            shadow_roots=int(payload.get("shadowRoots") or 0),
            gate_dismissed=bool(payload.get("gate_dismissed")),
            gate_note=payload.get("gate_note") or None,
        )

    except Exception as exc:
        return RenderResult(
            url=url, html="", rects={}, ok=False, error=f"{type(exc).__name__}: {exc}"
        )


def geometry_by_xpath(html: str, rects: dict[str, Rect]) -> dict[str, Rect]:
    """Rekey browser measurements from marker ids to lxml XPaths.

    Parsing here rather than in the caller keeps the marker convention private to this
    module, and guarantees the XPath is produced by the same lxml version that will later
    consume it.
    """
    from webgraph.dom.blocks import parse_html

    root = parse_html(html)
    tree = root.getroottree()
    geometry: dict[str, Rect] = {}

    for element in root.xpath(f"//*[@{MARKER_ATTRIBUTE}]"):
        marker = element.get(MARKER_ATTRIBUTE)
        if marker is not None and marker in rects:
            geometry[tree.getpath(element)] = rects[marker]

    return geometry
