"""Rendered fetching -- runs the page's JavaScript and measures where its text landed.

This module exists for two reasons, and the second is the important one:

1. Client-rendered pages have no content in their static HTML.
2. **Reading order needs geometry.** Source order is not visual order (MEMORY.md D10), and
   the only way to know where text actually sits is to lay the page out and measure it.

Binding measurements back to parsed elements
--------------------------------------------
Rects are collected in the browser but consumed by lxml, so the two need a shared key.
Recomputing an XPath in JavaScript to match lxml's `getpath()` output is fragile -- the
formats differ over when an index is emitted, and a mismatch fails silently by yielding no
geometry at all.

Instead the browser stamps every element with a `data-wg-id` attribute *before* serialising
the DOM. The attribute survives into the HTML we parse, so each element can be found again
and keyed by whatever path lxml itself produces. The key is generated by the same library
that consumes it, which removes the mismatch entirely.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Final, Literal

from webgraph.fetch.browser import shared_browser
from webgraph.types import Rect

__all__ = ["PLAYWRIGHT_AVAILABLE", "RenderConfig", "RenderResult", "geometry_by_xpath", "render_page"]

try:  # pragma: no cover - import guard depends on optional extra
    from playwright.sync_api import sync_playwright

    PLAYWRIGHT_AVAILABLE = True
except ImportError:  # pragma: no cover
    PLAYWRIGHT_AVAILABLE = False

MARKER_ATTRIBUTE: Final[str] = "data-wg-id"

_COLLECT_SCRIPT: Final[str] = """
() => {
  const MARKER = 'data-wg-id';
  const rects = {};
  let counter = 0;
  const walker = document.createTreeWalker(document.documentElement, NodeFilter.SHOW_ELEMENT);
  const nodes = [document.documentElement];
  while (walker.nextNode()) nodes.push(walker.currentNode);

  for (const el of nodes) {
    const id = String(counter++);
    el.setAttribute(MARKER, id);

    const style = window.getComputedStyle(el);
    if (style.display === 'none' || style.visibility === 'hidden' || style.opacity === '0') {
      continue;
    }
    const box = el.getBoundingClientRect();
    if (box.width <= 0 || box.height <= 0) continue;

    rects[id] = {
      // Page-relative, not viewport-relative: a scrolled viewport would otherwise
      // report negative coordinates for content above the fold.
      x: box.left + window.scrollX,
      y: box.top + window.scrollY,
      width: box.width,
      height: box.height,
    };
  }
  // Library versions are frequently only available at runtime. `jquery.min.js` carries no
  // version in its filename, but `jQuery.fn.jquery` reports it exactly. Reading these while
  // the page is live is the only reliable way to get them.
  const globals = {};
  const probe = (name, fn) => { try { const v = fn(); if (v) globals[name] = String(v); } catch (e) {} };

  probe('jQuery', () => window.jQuery && window.jQuery.fn && window.jQuery.fn.jquery);
  probe('React', () => window.React && window.React.version);
  probe('Vue.js', () => window.Vue && window.Vue.version);
  probe('Angular', () => window.ng && window.ng.version && window.ng.version.full);
  probe('Bootstrap', () => window.bootstrap && window.bootstrap.Tooltip && window.bootstrap.Tooltip.VERSION);
  probe('Modernizr', () => window.Modernizr && window.Modernizr._version);
  probe('Lodash', () => window._ && window._.VERSION);
  probe('Moment.js', () => window.moment && window.moment.version);
  probe('D3', () => window.d3 && window.d3.version);
  probe('GSAP', () => window.gsap && window.gsap.version);
  probe('Next.js', () => window.next && window.next.version);
  probe('Swiper', () => window.Swiper && window.Swiper.version);

  return { rects, html: document.documentElement.outerHTML, globals };
}
"""


@dataclass(frozen=True, slots=True)
class RenderConfig:
    timeout_ms: int = 30_000
    wait_until: Literal["commit", "domcontentloaded", "load", "networkidle"] = "load"
    """`load`, not `networkidle`.

    `networkidle` waits for 500ms of no network activity, which **never happens** on sites
    with analytics beacons, polling, websockets or video preloading. Measured against 24 real
    sites it timed out on 5 of them (21%) -- Shopify, Squarespace, Stripe, python.org and
    Figma -- losing those pages entirely. `load` plus an explicit settle is slightly earlier
    but actually fires."""

    viewport_width: int = 1440
    viewport_height: int = 900
    """Width matters for reading order -- a narrow viewport collapses a multi-column layout
    into one column, which changes the correct answer."""

    settle_ms: int = 900
    """Pause after load to let hydration and layout settle before measuring.

    Carries the weight that `networkidle` used to: most client-side frameworks finish
    hydrating within a few hundred milliseconds of `load`, and measuring before that captures
    the pre-hydration layout."""

    user_agent: str | None = None
    headless: bool = True
    reuse_browser: bool = True
    """Reuse the calling thread's browser rather than launching one per page.

    Launch is a fixed cost per page -- see `fetch/browser.py` for why the reuse is
    thread-local. Disable it to isolate a page that crashes the browser."""

    block_resources: tuple[str, ...] = ("image", "media", "font")
    """Skipped to cut bandwidth and time. Fonts are blocked deliberately: metrics shift
    slightly without them, but not enough to change column structure."""


@dataclass(frozen=True, slots=True)
class RenderResult:
    url: str
    html: str
    """Serialised *after* marker attributes were stamped, so the markers are present."""

    rects: dict[str, Rect]
    """Keyed by marker id, not XPath. Use `geometry_by_xpath` to rekey for the pipeline."""

    ok: bool
    error: str | None = None
    globals: dict[str, str] = field(default_factory=dict)
    """Library versions read from live JavaScript globals -- the only place most of them
    appear. `jquery.min.js` has no version in its filename; `jQuery.fn.jquery` has it exactly."""


def render_page(url: str, *, config: RenderConfig | None = None) -> RenderResult:
    """Load `url` in a headless browser and measure every visible element."""
    if not PLAYWRIGHT_AVAILABLE:
        return RenderResult(
            url=url,
            html="",
            rects={},
            ok=False,
            error="playwright is not installed; install the 'render' extra",
        )

    config = config or RenderConfig()

    def _measure(browser: Any) -> dict[str, Any]:
        """One page, in its own context so nothing leaks between pages of a crawl."""
        context = browser.new_context(
            viewport={"width": config.viewport_width, "height": config.viewport_height},
            user_agent=config.user_agent,
        )
        try:
            page = context.new_page()

            if config.block_resources:
                blocked = set(config.block_resources)
                page.route(
                    "**/*",
                    lambda route: (
                        route.abort()
                        if route.request.resource_type in blocked
                        else route.continue_()
                    ),
                )

            page.goto(url, timeout=config.timeout_ms, wait_until=config.wait_until)
            if config.settle_ms:
                page.wait_for_timeout(config.settle_ms)

            return dict(page.evaluate(_COLLECT_SCRIPT))
        finally:
            context.close()

    try:
        shared = shared_browser(headless=config.headless) if config.reuse_browser else None
        if shared is not None:
            payload: dict[str, Any] = _measure(shared)
        else:
            # No slot free, reuse disabled, or the shared launch failed: fall back to a
            # private browser so a render never depends on the pool being available.
            with sync_playwright() as driver:
                browser = driver.chromium.launch(headless=config.headless)
                try:
                    payload = _measure(browser)
                finally:
                    browser.close()

        rects = {
            key: Rect(
                x=float(value["x"]),
                y=float(value["y"]),
                width=float(value["width"]),
                height=float(value["height"]),
            )
            for key, value in payload["rects"].items()
        }
        raw_globals = payload.get("globals") or {}
        return RenderResult(
            url=url,
            html=str(payload["html"]),
            rects=rects,
            ok=True,
            globals={str(k): str(v) for k, v in raw_globals.items()},
        )

    except Exception as exc:
        return RenderResult(
            url=url, html="", rects={}, ok=False, error=f"{type(exc).__name__}: {exc}"
        )


def geometry_by_xpath(html: str, rects: dict[str, Rect]) -> dict[str, Rect]:
    """Rekey browser measurements from marker ids to lxml XPaths.

    Parsing here rather than in the caller keeps the marker convention private to this
    module, and guarantees the XPath is produced by the same lxml version that will later
    consume it.
    """
    from webgraph.dom.blocks import parse_html

    root = parse_html(html)
    tree = root.getroottree()
    geometry: dict[str, Rect] = {}

    for element in root.xpath(f"//*[@{MARKER_ATTRIBUTE}]"):
        marker = element.get(MARKER_ATTRIBUTE)
        if marker is not None and marker in rects:
            geometry[tree.getpath(element)] = rects[marker]

    return geometry
