"""Rendered fetching -- runs the page's JavaScript and measures where its text landed.

This module exists for two reasons, and the second is the important one:

1. Client-rendered pages have no content in their static HTML.
2. **Reading order needs geometry.** Source order is not visual order (MEMORY.md D10), and
   the only way to know where text actually sits is to lay the page out and measure it.

Binding measurements back to parsed elements
--------------------------------------------
Rects are collected in the browser but consumed by lxml, so the two need a shared key.
Recomputing an XPath in JavaScript to match lxml's `getpath()` output is fragile -- the
formats differ over when an index is emitted, and a mismatch fails silently by yielding no
geometry at all.

Instead the browser stamps every element with a `data-wg-id` attribute *before* serialising
the DOM. The attribute survives into the HTML we parse, so each element can be found again
and keyed by whatever path lxml itself produces. The key is generated by the same library
that consumes it, which removes the mismatch entirely.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Final, Literal

from webgraph.fetch.browser import shared_browser
from webgraph.types import Rect

__all__ = ["PLAYWRIGHT_AVAILABLE", "RenderConfig", "RenderResult", "geometry_by_xpath", "render_page"]

try:  # pragma: no cover - import guard depends on optional extra
    from playwright.sync_api import sync_playwright

    PLAYWRIGHT_AVAILABLE = True
except ImportError:  # pragma: no cover
    PLAYWRIGHT_AVAILABLE = False

MARKER_ATTRIBUTE: Final[str] = "data-wg-id"

_REVEAL_SCRIPT: Final[str] = """
() => {
  // Open content the page collapsed, without clicking anything.
  //
  // Accordions, FAQ sections and `<details>` blocks hold real content that no fetch and no
  // renderer sees, because it is `display:none` until someone interacts. Clicking is the
  // obvious way to reach it and the wrong one: a click can navigate, submit a form, open a
  // dialog that blocks the driver, or fire an analytics event on someone else's site.
  //
  // Everything here is a property or attribute change on the page's own DOM. Nothing is
  // clicked, no handler is invoked, and the page cannot navigate as a result.
  let opened = 0;

  for (const details of document.querySelectorAll('details:not([open])')) {
    details.open = true;
    opened++;
  }

  // ARIA disclosure pattern: a control says what it controls, and the panel says it is
  // hidden. Both halves are declared by the page, so honouring them is reading the page's
  // own description of itself rather than guessing at class names.
  for (const control of document.querySelectorAll('[aria-expanded="false"][aria-controls]')) {
    const ids = (control.getAttribute('aria-controls') || '').split(/\\s+/);
    let revealed = false;
    for (const id of ids) {
      const panel = document.getElementById(id);
      if (!panel) continue;
      panel.removeAttribute('hidden');
      if (panel.getAttribute('aria-hidden') === 'true') panel.setAttribute('aria-hidden', 'false');
      const style = window.getComputedStyle(panel);
      if (style.display === 'none') panel.style.setProperty('display', 'block', 'important');
      if (style.visibility === 'hidden') panel.style.setProperty('visibility', 'visible', 'important');
      if (parseFloat(style.height) === 0 && panel.scrollHeight > 0) {
        panel.style.setProperty('height', 'auto', 'important');
        panel.style.setProperty('overflow', 'visible', 'important');
      }
      revealed = true;
    }
    if (revealed) { control.setAttribute('aria-expanded', 'true'); opened++; }
  }

  return opened;
}
"""

MAX_RECORDED_REQUESTS: Final[int] = 400
"""Requests kept for fingerprinting. Only distinct hosts and paths carry information, and
an asset-heavy page can issue thousands."""

_COLLECT_SCRIPT: Final[str] = """
() => {
  const MARKER = 'data-wg-id';
  const rects = {};
  let counter = 0;
  const walker = document.createTreeWalker(document.documentElement, NodeFilter.SHOW_ELEMENT);
  const nodes = [document.documentElement];
  while (walker.nextNode()) nodes.push(walker.currentNode);

  for (const el of nodes) {
    const id = String(counter++);
    el.setAttribute(MARKER, id);

    const style = window.getComputedStyle(el);
    if (style.display === 'none' || style.visibility === 'hidden' || style.opacity === '0') {
      continue;
    }
    const box = el.getBoundingClientRect();
    if (box.width <= 0 || box.height <= 0) continue;

    rects[id] = {
      // Page-relative, not viewport-relative: a scrolled viewport would otherwise
      // report negative coordinates for content above the fold.
      x: box.left + window.scrollX,
      y: box.top + window.scrollY,
      width: box.width,
      height: box.height,
    };
  }
  // Library versions are frequently only available at runtime. `jquery.min.js` carries no
  // version in its filename, but `jQuery.fn.jquery` reports it exactly. Reading these while
  // the page is live is the only reliable way to get them.
  const globals = {};
  // Sentinel for "this is loaded but exposes no version". The Python side treats any value
  // that does not begin with a digit as presence without a version.
  const PRESENT = 'present';
  const probe = (name, fn) => { try { const v = fn(); if (v) globals[name] = String(v); } catch (e) {} };

  // Every global the page added, found by diffing against a pristine window.
  //
  // This is the signal that closes most of the gap with a browser extension. Hand-written
  // probes only find what someone thought to ask for; the diff finds `window.Tinybird`,
  // `window.__reactRouterVersion` and `window.lenisVersion` without anyone naming them
  // first, and the rules then map names to technologies.
  //
  // The baseline comes from a blank same-origin iframe rather than a hard-coded list,
  // because the set of standard globals differs by browser and by version.
  let customGlobals = [];
  try {
    const frame = document.createElement('iframe');
    frame.setAttribute('aria-hidden', 'true');
    frame.style.cssText = 'display:none;width:0;height:0';
    document.body.appendChild(frame);
    const baseline = new Set(Object.keys(frame.contentWindow));
    frame.remove();
    // Cap the list: a page that assigns hundreds of globals is doing something unusual, and
    // the interesting names are always near the front of the enumeration order anyway.
    customGlobals = Object.keys(window).filter((k) => !baseline.has(k)).slice(0, 400);
  } catch (e) { /* CSP can forbid the iframe; the explicit probes still apply. */ }

  probe('jQuery', () => window.jQuery && window.jQuery.fn && window.jQuery.fn.jquery);
  probe('React', () => window.React && window.React.version);
  probe('Vue.js', () => window.Vue && window.Vue.version);
  probe('Angular', () => window.ng && window.ng.version && window.ng.version.full);
  probe('Bootstrap', () => window.bootstrap && window.bootstrap.Tooltip && window.bootstrap.Tooltip.VERSION);
  probe('Modernizr', () => window.Modernizr && window.Modernizr._version);
  probe('Lodash', () => window._ && window._.VERSION);
  probe('Moment.js', () => window.moment && window.moment.version);
  probe('D3', () => window.d3 && window.d3.version);
  probe('GSAP', () => window.gsap && window.gsap.version);
  probe('Next.js', () => window.next && window.next.version);
  probe('Swiper', () => window.Swiper && window.Swiper.version);
  probe('PostHog', () => window.posthog && (window.posthog.version || window.posthog.config ? (window.posthog.version || PRESENT) : null));
  probe('Lenis', () => window.Lenis && (window.Lenis.version || PRESENT));
  probe('core-js', () => window['__core-js_shared__'] && PRESENT);
  probe('Alpine.js', () => window.Alpine && (window.Alpine.version || PRESENT));
  probe('Three.js', () => window.THREE && (window.THREE.REVISION || PRESENT));
  probe('Framer Motion', () => window.__FRAMER_MOTION__ && PRESENT);

  // Bundled frameworks expose no global at all -- a Vite build of React has no
  // `window.React`. They do leave private properties on the DOM nodes they own, which is
  // the only honest evidence that the framework is *running* rather than merely mentioned.
  const domKeyed = (prefixes) => {
    const roots = [document.body, document.getElementById('root'), document.getElementById('app')];
    const seen = [];
    for (const root of roots) {
      if (!root) continue;
      seen.push(root);
      for (let i = 0; i < root.children.length && seen.length < 40; i++) seen.push(root.children[i]);
    }
    for (const el of seen) {
      for (const key of Object.keys(el)) {
        for (const prefix of prefixes) {
          if (key.startsWith(prefix)) return true;
        }
      }
    }
    return false;
  };

  probe('React', () => {
    if (window.React && window.React.version) return window.React.version;
    return domKeyed(['__reactContainer$', '__reactFiber$', '__reactProps$', '__reactInternalInstance$'])
      ? PRESENT : null;
  });
  probe('Preact', () => domKeyed(['__preactattr_', '_prevVNode', '__k']) && !window.React ? PRESENT : null);
  probe('Vue.js', () => {
    if (window.Vue && window.Vue.version) return window.Vue.version;
    const el = document.querySelector('#app, [data-v-app]');
    return el && el.__vue_app__ ? (el.__vue_app__.version || PRESENT) : null;
  });
  probe('Svelte', () => document.querySelector('[class*=svelte-]') || domKeyed(['__svelte_meta']) ? PRESENT : null);
  probe('React Router', () => {
    if (window.__reactRouterVersion) return String(window.__reactRouterVersion);
    if (window.__reactRouterContext || window.__staticRouterHydrationData) return PRESENT;
    return document.querySelector('[data-discover="true"]') ? PRESENT : null;
  });

  // Versions, where the library exposes one somewhere other than a bare `.version`.
  probe('Facebook Pixel', () => window.fbq && window.fbq.version);
  probe('core-js', () => {
    const shared = window['__core-js_shared__'];
    if (!shared) return null;
    const versions = shared.versions;
    if (Array.isArray(versions) && versions.length && versions[0].version) return versions[0].version;
    return PRESENT;
  });
  probe('Lenis', () => window.lenisVersion || (window.lenis || document.documentElement.classList.contains('lenis') ? PRESENT : null));
  probe('PostHog', () => {
    const ph = window.posthog;
    if (ph) return ph.version || (ph.LIB_VERSION) || PRESENT;
    return window.__PosthogExtensions__ || window._POSTHOG_REMOTE_CONFIG ? PRESENT : null;
  });
  probe('Tinybird', () => window.Tinybird && PRESENT);

  const scripts = Array.from(document.scripts).map((s) => s.src).filter(Boolean).slice(0, 60);
  const links = Array.from(document.querySelectorAll('link[rel][href]'))
    .map((l) => l.rel + ' ' + l.href).slice(0, 60);

  return {
    rects,
    html: document.documentElement.outerHTML,
    globals,
    customGlobals,
    scripts,
    links,
  };
}
"""


@dataclass(frozen=True, slots=True)
class RenderConfig:
    timeout_ms: int = 30_000
    wait_until: Literal["commit", "domcontentloaded", "load", "networkidle"] = "load"
    """`load`, not `networkidle`.

    `networkidle` waits for 500ms of no network activity, which **never happens** on sites
    with analytics beacons, polling, websockets or video preloading. Measured against 24 real
    sites it timed out on 5 of them (21%) -- Shopify, Squarespace, Stripe, python.org and
    Figma -- losing those pages entirely. `load` plus an explicit settle is slightly earlier
    but actually fires."""

    viewport_width: int = 1440
    viewport_height: int = 900
    """Width matters for reading order -- a narrow viewport collapses a multi-column layout
    into one column, which changes the correct answer."""

    settle_ms: int = 900
    """Pause after load to let hydration and layout settle before measuring.

    Carries the weight that `networkidle` used to: most client-side frameworks finish
    hydrating within a few hundred milliseconds of `load`, and measuring before that captures
    the pre-hydration layout."""

    reveal_collapsed: bool = False
    """Open `<details>` and ARIA disclosure panels before measuring.

    Reaches content the page hides until someone interacts, without clicking anything -- see
    `_REVEAL_SCRIPT` for why clicking is the wrong tool. Off until measured; see MEMORY.md.
    """

    user_agent: str | None = None
    headless: bool = True
    reuse_browser: bool = True
    """Reuse the calling thread's browser rather than launching one per page.

    Launch is a fixed cost per page -- see `fetch/browser.py` for why the reuse is
    thread-local. Disable it to isolate a page that crashes the browser."""

    block_resources: tuple[str, ...] = ("image", "media", "font")
    """Skipped to cut bandwidth and time. Fonts are blocked deliberately: metrics shift
    slightly without them, but not enough to change column structure."""


@dataclass(frozen=True, slots=True)
class RenderResult:
    url: str
    html: str
    """Serialised *after* marker attributes were stamped, so the markers are present."""

    rects: dict[str, Rect]
    """Keyed by marker id, not XPath. Use `geometry_by_xpath` to rekey for the pipeline."""

    ok: bool
    error: str | None = None
    globals: dict[str, str] = field(default_factory=dict)
    """Library versions read from live JavaScript globals -- the only place most of them
    appear. `jquery.min.js` has no version in its filename; `jQuery.fn.jquery` has it exactly."""

    custom_globals: tuple[str, ...] = ()
    """Every global the page added, diffed against a pristine window.

    Hand-written probes only find what someone thought to name. This finds the rest --
    `Tinybird`, `__reactRouterVersion`, `lenisVersion` -- and is what closes most of the gap
    with a browser extension that can read the live heap."""

    requests: tuple[str, ...] = ()
    """Every URL the page requested while loading.

    A third-party service is frequently invisible in the markup and unmistakable in the
    network log: PostHog arrives as `us-assets.i.posthog.com/array/.../config.js`, and
    Cloudflare's bot management as a `/cdn-cgi/challenge-platform/` script."""

    cookies: dict[str, str] = field(default_factory=dict)
    """Cookies present after load, from the browser jar rather than the document's own
    `Set-Cookie`. Cookies set by a third-party script never appear in the main response."""

    scripts: tuple[str, ...] = ()
    """`src` of every script element after hydration, including ones injected at runtime."""

    links: tuple[str, ...] = ()
    """`rel href` of every link element, for manifest, preconnect and stylesheet signals."""


def render_page(url: str, *, config: RenderConfig | None = None) -> RenderResult:
    """Load `url` in a headless browser and measure every visible element."""
    if not PLAYWRIGHT_AVAILABLE:
        return RenderResult(
            url=url,
            html="",
            rects={},
            ok=False,
            error="playwright is not installed; install the 'render' extra",
        )

    config = config or RenderConfig()

    def _measure(browser: Any) -> dict[str, Any]:
        """One page, in its own context so nothing leaks between pages of a crawl."""
        context = browser.new_context(
            viewport={"width": config.viewport_width, "height": config.viewport_height},
            user_agent=config.user_agent,
        )
        try:
            page = context.new_page()

            # The network log is a first-class fingerprinting signal, not diagnostics: a
            # third-party service is often invisible in the markup and unmistakable here.
            # Capped, because an image-heavy page can issue hundreds of requests and only
            # the distinct hosts and paths carry information.
            requests: list[str] = []

            def _record(request: Any) -> None:
                if len(requests) < MAX_RECORDED_REQUESTS:
                    requests.append(str(request.url))

            page.on("request", _record)

            if config.block_resources:
                blocked = set(config.block_resources)
                page.route(
                    "**/*",
                    lambda route: (
                        route.abort()
                        if route.request.resource_type in blocked
                        else route.continue_()
                    ),
                )

            page.goto(url, timeout=config.timeout_ms, wait_until=config.wait_until)
            if config.settle_ms:
                page.wait_for_timeout(config.settle_ms)

            if config.reveal_collapsed:
                try:
                    revealed = int(page.evaluate(_REVEAL_SCRIPT) or 0)
                except Exception:
                    revealed = 0
                if revealed:
                    # Let layout settle: opening a panel reflows everything below it, and
                    # reading order is measured from geometry.
                    page.wait_for_timeout(250)

            payload = dict(page.evaluate(_COLLECT_SCRIPT))
            payload["requests"] = requests
            # From the jar, not from the document's own `Set-Cookie`: a cookie written by a
            # third-party script never appears in the main response headers.
            payload["cookies"] = {
                str(cookie.get("name", "")): str(cookie.get("value", ""))
                for cookie in context.cookies()
            }
            return payload
        finally:
            context.close()

    try:
        shared = shared_browser(headless=config.headless) if config.reuse_browser else None
        if shared is not None:
            payload: dict[str, Any] = _measure(shared)
        else:
            # No slot free, reuse disabled, or the shared launch failed: fall back to a
            # private browser so a render never depends on the pool being available.
            with sync_playwright() as driver:
                browser = driver.chromium.launch(headless=config.headless)
                try:
                    payload = _measure(browser)
                finally:
                    browser.close()

        rects = {
            key: Rect(
                x=float(value["x"]),
                y=float(value["y"]),
                width=float(value["width"]),
                height=float(value["height"]),
            )
            for key, value in payload["rects"].items()
        }
        raw_globals = payload.get("globals") or {}
        return RenderResult(
            url=url,
            html=str(payload["html"]),
            rects=rects,
            ok=True,
            globals={str(k): str(v) for k, v in raw_globals.items()},
            custom_globals=tuple(str(name) for name in payload.get("customGlobals") or ()),
            requests=tuple(str(item) for item in payload.get("requests") or ()),
            cookies={str(k): str(v) for k, v in (payload.get("cookies") or {}).items()},
            scripts=tuple(str(item) for item in payload.get("scripts") or ()),
            links=tuple(str(item) for item in payload.get("links") or ()),
        )

    except Exception as exc:
        return RenderResult(
            url=url, html="", rects={}, ok=False, error=f"{type(exc).__name__}: {exc}"
        )


def geometry_by_xpath(html: str, rects: dict[str, Rect]) -> dict[str, Rect]:
    """Rekey browser measurements from marker ids to lxml XPaths.

    Parsing here rather than in the caller keeps the marker convention private to this
    module, and guarantees the XPath is produced by the same lxml version that will later
    consume it.
    """
    from webgraph.dom.blocks import parse_html

    root = parse_html(html)
    tree = root.getroottree()
    geometry: dict[str, Rect] = {}

    for element in root.xpath(f"//*[@{MARKER_ATTRIBUTE}]"):
        marker = element.get(MARKER_ATTRIBUTE)
        if marker is not None and marker in rects:
            geometry[tree.getpath(element)] = rects[marker]

    return geometry
